BEGIN;

CREATE SEQUENCE site_role_seq;

CREATE SEQUENCE social_user_account_seq;

CREATE SEQUENCE social_user_seq;

CREATE SEQUENCE user_seq;

CREATE TABLE SITE_ROLE (
  ID        INT8         NOT NULL DEFAULT nextval('site_role_seq'),
  AUTHORITY VARCHAR(128) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SITE_USER (
  ID               INT8         NOT NULL DEFAULT nextval('user_seq'),
  ACCOUNT_EXPIRED  BOOLEAN      NOT NULL,
  ACCOUNT_LOCKED   BOOLEAN      NOT NULL,
  ACTIVE           BOOLEAN      NOT NULL,
  ENABLED          BOOLEAN      NOT NULL,
  PASSWORD         VARCHAR(512) NOT NULL,
  PASSWORD_EXPIRED BOOLEAN      NOT NULL,
  USERNAME         VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SOCIAL_USER (
  ID       INT8         NOT NULL DEFAULT nextval('social_user_seq'),
  ACTIVE   BOOLEAN      NOT NULL,
  username VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SOCIAL_USER_ACCOUNT (
  ID                    INT8         NOT NULL DEFAULT nextval('social_user_account_seq'),
  CREATE_DATE_LAST_POST TIMESTAMP,
  ENABLED               BOOLEAN      NOT NULL,
  LAST_POST_ID          VARCHAR(256),
  PASSWORD              VARCHAR(512) NOT NULL,
  SOCIAL_NETWORK        INT4         NOT NULL,
  SOCIAL_USER_ID        VARCHAR(128),
  USERNAME              VARCHAR(256) NOT NULL,
  USER_ID               INT8,
  accounts_ID           INT8         NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
  USER_ID INT8 NOT NULL,
  ROLE_ID INT8 NOT NULL
);

ALTER TABLE SITE_ROLE
ADD CONSTRAINT SITE_ROLE_AUTHORITY_UK UNIQUE (AUTHORITY);

ALTER TABLE SITE_USER
ADD CONSTRAINT SITE_USER_USERNAME_UK UNIQUE (USERNAME);

ALTER TABLE SOCIAL_USER
ADD CONSTRAINT SOCIAL_USER_USERNAME_UK UNIQUE (username);

ALTER TABLE SOCIAL_USER_ACCOUNT
ADD CONSTRAINT SOCIAL_USER_ACCOUNT_USERNAME_UK UNIQUE (USERNAME);

ALTER TABLE SOCIAL_USER_ACCOUNT
ADD CONSTRAINT USER_SOCIAL_ACCOUNT_SOCIAL_USER_FK
FOREIGN KEY (USER_ID)
REFERENCES SOCIAL_USER;

ALTER TABLE SOCIAL_USER_ACCOUNT
ADD CONSTRAINT SITE_USER_SOCIAL_USER_ACCOUNT_FK
FOREIGN KEY (USER_ID)
REFERENCES SITE_USER;

ALTER TABLE SOCIAL_USER_ACCOUNT
ADD CONSTRAINT SOCIAL_USER_SOCIAL_USER_ACCOUNT_FK
FOREIGN KEY (accounts_ID)
REFERENCES SOCIAL_USER;

ALTER TABLE USER_ROLE
ADD CONSTRAINT ROLE_USER_FK
FOREIGN KEY (ROLE_ID)
REFERENCES SITE_ROLE;

ALTER TABLE USER_ROLE
ADD CONSTRAINT USER_ROLE_FK
FOREIGN KEY (USER_ID)
REFERENCES SITE_USER;

COMMIT;